Improvements and fixes (#238)
* change codigniter4/shiled version to dev-develop

* Fix config namespaces in accordance with Codeigniter 4.2.6

* Apply Fix TypeError when Saving a User from PR - https://github.com/lonnieezell/Bonfire2/pull/194
Fix some return types

* Refactor of fix TypeError when Saving a User

* Update Auth Config file

* Fix actions when saving user settings
Added actions for Email2FA and EmailActivator

* Remove unneeded methods from auth actions Email2FA and EmailActivator

* include zxcvbn.js file and fix path to zxcvbn.js using asset_link

* include zxcvbn.js file and fix path to zxcvbn.js using asset_link

* include zxcvbn.js file and fix path to zxcvbn.js using asset_link

* update zxcvbn.js to v4.4.2

* change tests namespaces

* remove route namespaces
define route variable

* remove return type

* run cs-fix

* remove unneeded file spark as it is a part of framework

* composer update

* fix tests

* remove unneeded commented debug line

* run cs-fix

* update shield and get rid of unit test errors 1 and 2
since in the last commit shild have merged my PR that fix UserModel
--------------------

There were 3 errors:

1) Tests\Auth\AdminAccessTest::testAdminsCanAccess
Error: Call to a member function set() on null

/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Models/UserModel.php:347
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Authentication/Authenticators/Session.php:880
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Filters/SessionAuth.php:49
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Filters/Filters.php:173
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:455
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:351
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:187
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:219
/Users/kpeu3u/GitProjects/Forks/Bonfire2/tests/Auth/AdminAccessTest.php:34
phpvfscomposer:///Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/phpunit/phpunit/phpunit:97
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/bin/phpunit:115

2) Tests\Auth\AdminAccessTest::testCannotAccessAdminWithoutPermission
Error: Call to a member function set() on null

/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Models/UserModel.php:347
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Authentication/Authenticators/Session.php:880
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Filters/SessionAuth.php:49
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Filters/Filters.php:173
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:455
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:351
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:187
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:219
/Users/kpeu3u/GitProjects/Forks/Bonfire2/tests/Auth/AdminAccessTest.php:51
phpvfscomposer:///Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/phpunit/phpunit/phpunit:97
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/bin/phpunit:115

3) Tests\Auth\AdminAccessTest::testCannotViewNavItemsWithoutPermission
Error: Call to a member function set() on null

/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Models/UserModel.php:347
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Authentication/Authenticators/Session.php:880
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Filters/SessionAuth.php:49
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Filters/Filters.php:173
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:455
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:351
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:187
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:219
/Users/kpeu3u/GitProjects/Forks/Bonfire2/tests/Auth/AdminAccessTest.php:70
phpvfscomposer:///Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/phpunit/phpunit/phpunit:97
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/bin/phpunit:115

ERRORS!
Tests: 105, Assertions: 259, Errors: 3.

* remove Authentication\Actions and revert user settings view