update shield and get rid of unit test errors 1 and 2 since in the last commit shild have merged my PR that fix UserModel --------------------
There were 3 errors:

1) Tests\Auth\AdminAccessTest::testAdminsCanAccess
Error: Call to a member function set() on null

/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Models/UserModel.php:347
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Authentication/Authenticators/Session.php:880
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Filters/SessionAuth.php:49
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Filters/Filters.php:173
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:455
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:351
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:187
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:219
/Users/kpeu3u/GitProjects/Forks/Bonfire2/tests/Auth/AdminAccessTest.php:34
phpvfscomposer:///Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/phpunit/phpunit/phpunit:97
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/bin/phpunit:115

2) Tests\Auth\AdminAccessTest::testCannotAccessAdminWithoutPermission
Error: Call to a member function set() on null

/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Models/UserModel.php:347
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Authentication/Authenticators/Session.php:880
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Filters/SessionAuth.php:49
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Filters/Filters.php:173
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:455
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:351
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:187
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:219
/Users/kpeu3u/GitProjects/Forks/Bonfire2/tests/Auth/AdminAccessTest.php:51
phpvfscomposer:///Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/phpunit/phpunit/phpunit:97
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/bin/phpunit:115

3) Tests\Auth\AdminAccessTest::testCannotViewNavItemsWithoutPermission
Error: Call to a member function set() on null

/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Models/UserModel.php:347
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Authentication/Authenticators/Session.php:880
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/shield/src/Filters/SessionAuth.php:49
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Filters/Filters.php:173
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:455
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/CodeIgniter.php:351
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:187
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/codeigniter4/framework/system/Test/FeatureTestTrait.php:219
/Users/kpeu3u/GitProjects/Forks/Bonfire2/tests/Auth/AdminAccessTest.php:70
phpvfscomposer:///Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/phpunit/phpunit/phpunit:97
/Users/kpeu3u/GitProjects/Forks/Bonfire2/vendor/bin/phpunit:115

ERRORS!
Tests: 105, Assertions: 259, Errors: 3.