Update LogsController.php (#451)
The urls

- /admin/settings/users

- /admin/users/1

cause

RuntimeException: View not found for component: button-container

at

VENDORPATH/lonnieezell/bonfire/src/View/ComponentRenderer.php at line 231